# Generated by Django 4.1.2 on 2022-11-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('-id',)},
        ),
    ]
