# Generated by Django 4.1.2 on 2022-11-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='follower_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
